sudo: required
language: node_js
dist: trusty
node_js:
  - "node"
sudo: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - default-jre
      - default-jdk
      - oracle-java8-set-default
      - google-chrome-stable
env:
  - JAVA_HOME="/usr/lib/jvm/java-8-oracle"
before_script:
  - jdk_switcher use oraclejdk8
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
  - yarn
  - npm run build
  - npm run launch-build &
  - sleep 1 # give the web server time to start
  - curl http://localhost:3000 # check that we can reach the web server
  - npm run e2e
  - npm run format-e2e-reports -- -b false
  - npm run kill-background
