language: node_js
os:
  - linux
node_js:
  - "node"
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - yarn
  - npm run build
  - npm run launch-build &
  - sleep 1 # give the web server time to start
  - npm run e2e
